# Site settings
title: Backing's blog 
email: kuangchanglang@163.com
description: > # this means to ignore newlines until "baseurl:"
  Somtimes I feel lost, I need to find a way out.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kuangchanglang.github.io" # the base hostname & protocol for your site
twitter_username: noname 
github_username: kuangchanglang 

# Build settings
markdown: kramdown
