# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    input: GFM

paginate: 5
paginate_path: "/blog/page/:num/"
comments: true

#source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: backing 
description: "backing's home"
keywords: "blog, python, golang, backend, docker, web"
url: http://kuangchanglang.com
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/kuangchanglang/
disqus_shortname: "kuangchanglang"
disqus_site_shortname: "kuangchanglang"

# Author settings
author:
  name      : Changlang Kuang 
  job       : Growing Backend Programmer 
  bio       : "Be more effective on stuff you have to do, that earns you time to enjoy anything you love."
  thumb     : /images/author.jpg
  email     : kuangchanglang@163.com
  url       : http://kuangchanglang.com
  github    : http://github.com/kuangchanglang
  weibo     : http://weibo.com/backinglang
  facebook  : https://www.facebook.com/profile.php?id=100010619612909
  linkedin  : https://www.linkedin.com/in/changlang-kuang-7955b055

# navbar pages
navbar:
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog
  - slug: about
    title: About

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
